// Curated list of country calling codes — common origins for hotel guests.
// Not exhaustive; ordered roughly by likely frequency, Italy first.
export const PHONE_PREFIXES = [
  { code: "+39", country: "Italia", flag: "🇮🇹" },
  { code: "+33", country: "Francia", flag: "🇫🇷" },
  { code: "+49", country: "Germania", flag: "🇩🇪" },
  { code: "+44", country: "Regno Unito", flag: "🇬🇧" },
  { code: "+1", country: "USA / Canada", flag: "🇺🇸" },
  { code: "+34", country: "Spagna", flag: "🇪🇸" },
  { code: "+41", country: "Svizzera", flag: "🇨🇭" },
  { code: "+43", country: "Austria", flag: "🇦🇹" },
  { code: "+31", country: "Paesi Bassi", flag: "🇳🇱" },
  { code: "+32", country: "Belgio", flag: "🇧🇪" },
  { code: "+351", country: "Portogallo", flag: "🇵🇹" },
  { code: "+30", country: "Grecia", flag: "🇬🇷" },
  { code: "+353", country: "Irlanda", flag: "🇮🇪" },
  { code: "+45", country: "Danimarca", flag: "🇩🇰" },
  { code: "+46", country: "Svezia", flag: "🇸🇪" },
  { code: "+47", country: "Norvegia", flag: "🇳🇴" },
  { code: "+358", country: "Finlandia", flag: "🇫🇮" },
  { code: "+48", country: "Polonia", flag: "🇵🇱" },
  { code: "+420", country: "Repubblica Ceca", flag: "🇨🇿" },
  { code: "+36", country: "Ungheria", flag: "🇭🇺" },
  { code: "+40", country: "Romania", flag: "🇷🇴" },
  { code: "+7", country: "Russia / Kazakistan", flag: "🇷🇺" },
  { code: "+380", country: "Ucraina", flag: "🇺🇦" },
  { code: "+90", country: "Turchia", flag: "🇹🇷" },
  { code: "+972", country: "Israele", flag: "🇮🇱" },
  { code: "+971", country: "Emirati Arabi Uniti", flag: "🇦🇪" },
  { code: "+966", country: "Arabia Saudita", flag: "🇸🇦" },
  { code: "+20", country: "Egitto", flag: "🇪🇬" },
  { code: "+27", country: "Sudafrica", flag: "🇿🇦" },
  { code: "+55", country: "Brasile", flag: "🇧🇷" },
  { code: "+52", country: "Messico", flag: "🇲🇽" },
  { code: "+54", country: "Argentina", flag: "🇦🇷" },
  { code: "+56", country: "Cile", flag: "🇨🇱" },
  { code: "+61", country: "Australia", flag: "🇦🇺" },
  { code: "+64", country: "Nuova Zelanda", flag: "🇳🇿" },
  { code: "+81", country: "Giappone", flag: "🇯🇵" },
  { code: "+82", country: "Corea del Sud", flag: "🇰🇷" },
  { code: "+86", country: "Cina", flag: "🇨🇳" },
  { code: "+91", country: "India", flag: "🇮🇳" },
  { code: "+62", country: "Indonesia", flag: "🇮🇩" },
  { code: "+65", country: "Singapore", flag: "🇸🇬" },
  { code: "+66", country: "Thailandia", flag: "🇹🇭" },
  { code: "+84", country: "Vietnam", flag: "🇻🇳" },
  { code: "+63", country: "Filippine", flag: "🇵🇭" },
  { code: "+92", country: "Pakistan", flag: "🇵🇰" },
] as const;

export const DEFAULT_PHONE_PREFIX = "+39";
