// Curated list of country calling codes — common origins for hotel guests.
// Not exhaustive; ordered roughly by likely frequency, Italy first.
// `iso` is the ISO 3166-1 alpha-2 code used to render a colored SVG flag via
// the country-flag-icons package (emoji flags render as plain text on some
// platforms, notably Windows, so we avoid relying on emoji font support).
export const PHONE_PREFIXES = [
  { code: "+39", country: "Italia", iso: "IT" },
  { code: "+33", country: "Francia", iso: "FR" },
  { code: "+49", country: "Germania", iso: "DE" },
  { code: "+44", country: "Regno Unito", iso: "GB" },
  { code: "+1", country: "USA / Canada", iso: "US" },
  { code: "+34", country: "Spagna", iso: "ES" },
  { code: "+41", country: "Svizzera", iso: "CH" },
  { code: "+43", country: "Austria", iso: "AT" },
  { code: "+31", country: "Paesi Bassi", iso: "NL" },
  { code: "+32", country: "Belgio", iso: "BE" },
  { code: "+351", country: "Portogallo", iso: "PT" },
  { code: "+30", country: "Grecia", iso: "GR" },
  { code: "+353", country: "Irlanda", iso: "IE" },
  { code: "+45", country: "Danimarca", iso: "DK" },
  { code: "+46", country: "Svezia", iso: "SE" },
  { code: "+47", country: "Norvegia", iso: "NO" },
  { code: "+358", country: "Finlandia", iso: "FI" },
  { code: "+48", country: "Polonia", iso: "PL" },
  { code: "+420", country: "Repubblica Ceca", iso: "CZ" },
  { code: "+36", country: "Ungheria", iso: "HU" },
  { code: "+40", country: "Romania", iso: "RO" },
  { code: "+7", country: "Russia / Kazakistan", iso: "RU" },
  { code: "+380", country: "Ucraina", iso: "UA" },
  { code: "+90", country: "Turchia", iso: "TR" },
  { code: "+972", country: "Israele", iso: "IL" },
  { code: "+971", country: "Emirati Arabi Uniti", iso: "AE" },
  { code: "+966", country: "Arabia Saudita", iso: "SA" },
  { code: "+20", country: "Egitto", iso: "EG" },
  { code: "+27", country: "Sudafrica", iso: "ZA" },
  { code: "+55", country: "Brasile", iso: "BR" },
  { code: "+52", country: "Messico", iso: "MX" },
  { code: "+54", country: "Argentina", iso: "AR" },
  { code: "+56", country: "Cile", iso: "CL" },
  { code: "+61", country: "Australia", iso: "AU" },
  { code: "+64", country: "Nuova Zelanda", iso: "NZ" },
  { code: "+81", country: "Giappone", iso: "JP" },
  { code: "+82", country: "Corea del Sud", iso: "KR" },
  { code: "+86", country: "Cina", iso: "CN" },
  { code: "+91", country: "India", iso: "IN" },
  { code: "+62", country: "Indonesia", iso: "ID" },
  { code: "+65", country: "Singapore", iso: "SG" },
  { code: "+66", country: "Thailandia", iso: "TH" },
  { code: "+84", country: "Vietnam", iso: "VN" },
  { code: "+63", country: "Filippine", iso: "PH" },
  { code: "+92", country: "Pakistan", iso: "PK" },
] as const;

export const DEFAULT_PHONE_PREFIX = "+39";
