// Curated list of country calling codes — common origins for hotel guests.
// Not exhaustive; ordered roughly by likely frequency, Italy first.
export const PHONE_PREFIXES = [
  { code: "+39", country: "Italia" },
  { code: "+33", country: "Francia" },
  { code: "+49", country: "Germania" },
  { code: "+44", country: "Regno Unito" },
  { code: "+1", country: "USA / Canada" },
  { code: "+34", country: "Spagna" },
  { code: "+41", country: "Svizzera" },
  { code: "+43", country: "Austria" },
  { code: "+31", country: "Paesi Bassi" },
  { code: "+32", country: "Belgio" },
  { code: "+351", country: "Portogallo" },
  { code: "+30", country: "Grecia" },
  { code: "+353", country: "Irlanda" },
  { code: "+45", country: "Danimarca" },
  { code: "+46", country: "Svezia" },
  { code: "+47", country: "Norvegia" },
  { code: "+358", country: "Finlandia" },
  { code: "+48", country: "Polonia" },
  { code: "+420", country: "Repubblica Ceca" },
  { code: "+36", country: "Ungheria" },
  { code: "+40", country: "Romania" },
  { code: "+7", country: "Russia / Kazakistan" },
  { code: "+380", country: "Ucraina" },
  { code: "+90", country: "Turchia" },
  { code: "+972", country: "Israele" },
  { code: "+971", country: "Emirati Arabi Uniti" },
  { code: "+966", country: "Arabia Saudita" },
  { code: "+20", country: "Egitto" },
  { code: "+27", country: "Sudafrica" },
  { code: "+55", country: "Brasile" },
  { code: "+52", country: "Messico" },
  { code: "+54", country: "Argentina" },
  { code: "+56", country: "Cile" },
  { code: "+61", country: "Australia" },
  { code: "+64", country: "Nuova Zelanda" },
  { code: "+81", country: "Giappone" },
  { code: "+82", country: "Corea del Sud" },
  { code: "+86", country: "Cina" },
  { code: "+91", country: "India" },
  { code: "+62", country: "Indonesia" },
  { code: "+65", country: "Singapore" },
  { code: "+66", country: "Thailandia" },
  { code: "+84", country: "Vietnam" },
  { code: "+63", country: "Filippine" },
  { code: "+92", country: "Pakistan" },
] as const;

export const DEFAULT_PHONE_PREFIX = "+39";
