// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run against the direct (non-pooled) connection when one is
    // provided — needed for poolers like Supabase's PgBouncer in transaction
    // mode, which the schema/migration engine can't run DDL through. Plain
    // setups (local Postgres, Neon, Vercel Postgres) only need DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
