-- Split guestName into guestFirstName/guestLastName, add structured baggage
-- and price adjustment fields to Transfer. Hand-written (not autogenerated)
-- so existing guestName values are backfilled instead of dropped blind.

-- AlterTable: TransferRequest — add nullable name columns first
ALTER TABLE "TransferRequest" ADD COLUMN     "guestFirstName" TEXT,
ADD COLUMN     "guestLastName" TEXT;

-- Backfill: split on the last space — "Sophie Dubois" -> "Sophie" / "Dubois".
-- No space at all -> whole value becomes the last name (keeps surname search working).
UPDATE "TransferRequest" SET
  "guestFirstName" = CASE WHEN position(' ' in reverse("guestName")) > 0
    THEN left("guestName", length("guestName") - position(' ' in reverse("guestName")))
    ELSE '' END,
  "guestLastName" = CASE WHEN position(' ' in reverse("guestName")) > 0
    THEN right("guestName", position(' ' in reverse("guestName")) - 1)
    ELSE "guestName" END;

ALTER TABLE "TransferRequest" ALTER COLUMN "guestFirstName" SET NOT NULL,
ALTER COLUMN "guestLastName" SET NOT NULL;

ALTER TABLE "TransferRequest" DROP COLUMN "guestName";

-- AlterTable: Transfer — same split, plus new baggage/adjustment columns
ALTER TABLE "Transfer" ADD COLUMN     "guestFirstName" TEXT,
ADD COLUMN     "guestLastName" TEXT;

UPDATE "Transfer" SET
  "guestFirstName" = CASE WHEN position(' ' in reverse("guestName")) > 0
    THEN left("guestName", length("guestName") - position(' ' in reverse("guestName")))
    ELSE '' END,
  "guestLastName" = CASE WHEN position(' ' in reverse("guestName")) > 0
    THEN right("guestName", position(' ' in reverse("guestName")) - 1)
    ELSE "guestName" END;

ALTER TABLE "Transfer" ALTER COLUMN "guestFirstName" SET NOT NULL,
ALTER COLUMN "guestLastName" SET NOT NULL;

ALTER TABLE "Transfer" DROP COLUMN "guestName";

ALTER TABLE "Transfer" ADD COLUMN     "bagsCabin" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bagsStandard" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bagsLarge" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "priceAdjustmentType" TEXT,
ADD COLUMN     "priceAdjustmentAmount" DOUBLE PRECISION;

-- RenameIndex-equivalent (old index referenced guestName, drop + recreate on guestLastName)
DROP INDEX IF EXISTS "Transfer_guestName_idx";
CREATE INDEX "Transfer_guestLastName_idx" ON "Transfer"("guestLastName");
